#!/usr/bin/env bash
# Prepare a node: check Docker, create directories, build/pull images, show the
# capacity plan, write tb.env. Run this first.
#   TB_ROOT=/mnt/nvme/tpch-tb bash setup.sh
#   TB_ROOT=/mnt/nvme/tpch-tb SMOKE=1 bash setup.sh   # also run the SF=1 test

set -uo pipefail
HERE=$(cd "$(dirname "$0")" && pwd); . "$HERE/config.sh"; . "$HERE/lib.sh"

SMOKE=${SMOKE:-0}
ENVFILE="$HERE/tb.env"

echo "=============================================================="
echo " Setup: preparing this node for the TPC-H benchmark"
echo "=============================================================="

# ---- 1. docker ---------------------------------------------------------------
echo; echo "[1/6] container runtime"
command -v docker >/dev/null 2>&1 || die "docker not found. Install Docker, then re-run."
if ! docker info >/dev/null 2>&1; then
  die "cannot talk to the docker daemon.
     Either add your user to the group and re-login:  sudo usermod -aG docker $(id -un)
     or run this script with sudo."
fi
echo "  ok: $(docker --version | cut -d, -f1)"

# ---- 2. node ------------------------------------------------------------------
echo; echo "[2/6] node"
RAM=$(node_ram_bytes); CORES=$(node_cores)
echo "  cores: $CORES"
echo "  RAM:   $(hr "$RAM")"
resolve_sizing
echo "  derived sizing: CPUS=$CPUS MEM=$MEM DUCK_MEM=$DUCK_MEM INNODB_POOL=$INNODB_POOL"

# ---- 3. directories -----------------------------------------------------------
echo; echo "[3/6] working directories under TB_ROOT=$TB_ROOT"
if [ "$TB_ROOT" = "/data/tpch-tb" ]; then
  echo "  NOTE: TB_ROOT is the default. Point it at your big disk instead, e.g."
  echo "        TB_ROOT=/mnt/nvme/tpch-tb bash setup.sh"
fi
for d in "$TB_ROOT" "$RESULTS_DIR" "$STATE_DIR" "$TEMP_DIR" "$DUCKDB_DATADIR" "$INNODB_DATADIR"; do
  mkdir -p "$d" 2>/dev/null || die "cannot create $d (permissions? wrong mount?)"
  printf '  %-46s free %s\n' "$d" "$(hr "$(free_bytes "$d")")"
done
touch "$TB_ROOT/.writetest" 2>/dev/null && rm -f "$TB_ROOT/.writetest" || die "$TB_ROOT is not writable"

# ---- 4. images ----------------------------------------------------------------
echo; echo "[4/6] container images"
ensure_images
ensure_report_image
for i in "$ENGINE_IMAGE" "$DUCKDB_IMAGE" "$GEN_IMAGE" "$REPORT_IMAGE"; do
  printf '  [ ok ] %s\n' "$i"
done

# ---- 4b. host tunables ---------------------------------------------------------
echo; echo "[4b] host tunables (swappiness, dirty ratios, open files)"
if [ "${TUNE:-0}" = 1 ]; then
  bash "$HERE/tune-node.sh" apply 2>&1 | sed 's/^/  /'
else
  bash "$HERE/tune-node.sh" --dry-run 2>&1 | sed -n '/Current -> desired/,/^$/p' | sed 's/^/  /'
  echo "  -> to apply these:  bash tune-node.sh          (add PERSIST=1 to survive reboot)"
  echo "  -> or re-run setup: TUNE=1 bash setup.sh"
fi

# ---- 5. env file --------------------------------------------------------------
echo; echo "[5/6] writing $ENVFILE"
# IMPORTANT: only SF-independent settings go in here. DATA_DIR, the datadirs and
# NATIVE_DB are derived from $SF by config.sh on every run - exporting them once
# would pin them to whatever SF setup.sh happened to see, so a later
# `SF=200 bash run-all.sh` would write into the SF1000 directories.
cat > "$ENVFILE" <<EOF
# Generated by setup.sh on $(date -u +%FT%TZ)
# Source this before every harness command:   source $(basename "$ENVFILE")
# SF-derived paths are intentionally absent - they follow \$SF automatically.
export TB_ROOT="$TB_ROOT"
export RESULTS_DIR="$RESULTS_DIR"
export STATE_DIR="$STATE_DIR"
export TEMP_DIR="$TEMP_DIR"
export ENGINE_IMAGE="$ENGINE_IMAGE"
export DUCKDB_IMAGE="$DUCKDB_IMAGE"
export GEN_IMAGE="$GEN_IMAGE"
export REPORT_IMAGE="$REPORT_IMAGE"
EOF
echo "  written"

# ---- 6. plan + preflight -------------------------------------------------------
echo; echo "[6/6] capacity plan"
bash "$HERE/plan.sh" 2>&1 | sed -n '/RECOMMENDED PLAN/,$p'

echo
echo "=============================================================="
if [ "$SMOKE" = 1 ]; then
  echo " Running the SF=1 smoke test (a few minutes) ..."
  echo "=============================================================="
  if SF=1 LEGS="duckdb native" bash "$HERE/run-all.sh"; then
    echo
    echo " SMOKE TEST PASSED - the full pipeline works on this node."
  else
    die "smoke test FAILED - fix this before starting the long run"
  fi
else
  echo " Setup complete."
  echo
  echo " Strongly recommended next step - validate the whole pipeline in minutes:"
  echo "     SF=1 LEGS=\"duckdb native\" bash run-all.sh"
  echo
  echo " Then the real run:"
  echo "     source $(basename "$ENVFILE")"
  echo "     bash run-all.sh                 # Phase 1: SF1000 DuckDB"
  echo "     bash report.sh                  # report + charts"
fi
echo "=============================================================="
